Draft: Closing #2
conal/agda-hardware pull request #10
Opened 2021-06-09 15:40 UTC by VictorCMiraldo

I just started working on closing #2, yet, because I had to do a few more changes than expected, I decided to make a draft with it so @conal can start giving some feedback on whether those changes were necessary or whether I'm using the constructions on the wrong way :)

2021-06-09 16:56 UTC, conal requested changes
I'm glad to see you working on these homomorphism properties! The lovely, contravariant nature of the properties are delightful and worth bringing out in simple, general, poetic form.

2021-06-09 16:56 UTC, conal commented on Routing/Homomorphism.agda
> +swizzle-∘-lemma a x = {!!}
If you quantify over `Swizzle`s instead of routing morphisms (wrapped `Swizzle`s), the lemma statement will be prettier.

Since the lemma are about rather than routing morphisms (though the distinction is minor), they perhaps belong in `Index.Properties` (since `Index` defines `swizzle`).

2021-06-09 16:56 UTC, conal commented on Routing/Homomorphism.agda
> +swizzle-id-lemma : (a : Ty) (x : toObj a) → swizzle {a = a} (λ y → y) x ≡ x
I'd say `id` instead of `(λ y → y)` here.

2021-06-09 16:56 UTC, conal commented on Routing/Homomorphism.agda
> +swizzle-id-lemma `⊤         _ = ≡-refl
I'd drop the "`-lemma`" for succinctness. The lemma-ness is in the type, right?

2021-06-09 16:56 UTC, conal commented on Routing/Homomorphism.agda
> +    { F-id = λ { {a = a} {x = x} → swizzle-id-lemma a x }
I think here you can more simply write "`λ {a x} → swizzle-id-lemma a x`". Or better, "`λ {a} → swizzle-id-lemma a`", making `x` an implicit argument.

2021-06-09 16:56 UTC, conal commented on Routing/Homomorphism.agda
> +swizzle-∘-lemma a x = {!!}
I think the value arguments can be deduced and hence conveniently made implicit arguments, resulting in more succinct definitions and uses.

2021-06-09 16:56 UTC, conal commented on Ty.agda
> +toObj (a `⇛ b) = toObj a ⇛ toObj b
I think you can use `Fₒ a` in place of `toObj a`, and drop the top-level `toObj` definition. `Fₒ` is the object-mapping part of a functor and is used in many places in the project.

2021-06-09 19:09 UTC, VictorCMiraldo commented on Ty.agda
> +toObj (a `⇛ b) = toObj a ⇛ toObj b
I see! That would make sense, I still have to internalize how you divided everything! :)

2021-06-09 22:49 UTC, conal commented on Routing/Homomorphism.agda
> +          → swizzle (f ∘ g) x ≡ (swizzle g ∘ swizzle f) x
Indeed, these signatures do look prettier (more poetic). Another cosmetic tweak would be using `_≗_` from the standard library. Or, if you make the value parameter implicit (which I recommend here), then I think you can use `_≈_`:

``` agda
swizzle id ≈ id
swizzle (f ∘ g) ≈ swizzle g ∘ swizzle f
```

In other words, `swizzle` is a contravariant endofunctor. Wrap up `Swizzle` as a category, and we get a simple, covariant (non-endo) functor, which is what happens in `Routing`.

I’ve gotten a lot of useful insight from coaxing this kind of pattern starting from a vague whiff, step by step, until it expresses itself in its most clear, general, and simple form.

2021-06-10 18:29 UTC, VictorCMiraldo commented on Routing/Homomorphism.agda
> +swizzle-∘-lemma a x = {!!}
I often leave arguments I need to do induction on as explicit, just because writing the proofs is easier. I'm happy either way

2021-06-10 18:29 UTC, VictorCMiraldo commented on Routing/Homomorphism.agda
> +    { F-id = λ { {a = a} {x = x} → swizzle-id-lemma a x }
That's better indeed

2021-06-10 19:16 UTC, conal commented on Routing/Homomorphism.agda
> +swizzle-∘-lemma a x = {!!}
> I often leave arguments I need to do induction on as explicit, just because writing the proofs is easier.

Me, too, and in this case, I’d expect induction on `a : Ty` rather than on `x : Fₒ a`.

2021-06-10 19:30 UTC, conal commented on Routing/Homomorphism.agda
> +          → swizzle (f ∘ g) x ≡ (swizzle g ∘ swizzle f) x
Hm! When I wrote out this proof in agda-machines, I used `≡-Reasoning` rather than `≈-Reasoning`.

It hadn’t occurred to met that Agda’s treatment of implicits might prevent us from using equivalence reasoning on functions with implicit arguments. If indeed it does, then maybe the function category should use explicit rather than implicit extensional equality. I switched from explicit to implicit for functions, and I’m afraid I don’t quite remember my motivation. Let’s explore this question in a different PR.

2021-06-11 11:34 UTC, VictorCMiraldo commented on Routing/Homomorphism.agda
> +swizzle-∘-lemma a x = {!!}
Well, I'd be hoping to prove this without induction altogether :)

2021-06-11 11:37 UTC, VictorCMiraldo commented on Routing/Homomorphism.agda
> +          → swizzle (f ∘ g) x ≡ (swizzle g ∘ swizzle f) x
I was thinking around these lines:
```
    swizzle (f ∘ g) x -- Note we need the x here to let Agda reduce the def for swizzle
  ≡⟨ refl && ∘-assoc ⟩
   tabulate ((lookup x ∘ f) ∘ g)
  ≡⟨ cong tabulate refl ⟩
   tabulate (id (lookup x ∘ f) ∘ g)
  ≡⟨ cong tabulate (fun-ext lookup-tabulate-id) ⟩
   tabulate (lookup (tabulate (lookup x ∘ f)) ∘ g)
  ≡⟨ ≡-refl ⟩
   swizzle g (tabulate (lookup x ∘ f))
  ∎
```

2021-06-11 20:13 UTC, conal commented on Routing/Homomorphism.agda
> +          → swizzle (f ∘ g) x ≡ (swizzle g ∘ swizzle f) x
> we need to pass a proof that the arguments to `tabulate` are equal as the second parameter of that `cong`; but the arguments to tabulate are themselves functions, which require function extensionality to be proven propositionally equal

Are you sure you need the functions to be (propositionally) *equal* rather than something weaker?

2021-06-12 20:19 UTC, conal commented on Routing/Homomorphism.agda
> +          → swizzle (f ∘ g) x ≡ (swizzle g ∘ swizzle f) x
(I think you're almost there!)

2021-06-13 10:10 UTC, VictorCMiraldo commented on Routing/Homomorphism.agda
> +          → swizzle (f ∘ g) x ≡ (swizzle g ∘ swizzle f) x
We don't need propositionally equal arguments to `tabulate`, pointwise equal is just fine. I did try that before, but backtracked after I kept getting some Agda errors on "missing instances", which threw me off from my actual mistake: I was missing a step on the proof! After careful pen-and-paper review, I found the missing step and fixed it :)

I still couldn't get rid of that pesky transitivity in the argument of `~~-tabulate` and I do have to stop for today.

Happy to address any further comments @conal !

2021-06-13 17:22 UTC, conal approved these changes
Looks good. Thanks for seeing it through!

2021-06-13 17:22 UTC, merged