Complete Primitive Homomorphism proofs
conal/agda-hardware pull request #12
Opened 2021-06-11 00:55 UTC by sseefried

2021-06-11 01:24 UTC, conal requested changes
Looking good! A few questions and suggestions.

2021-06-11 01:24 UTC, conal commented on Primitive/Homomorphism.agda
> +        ≡⟨ _≡_.refl ⟩
More simply, `≡⟨⟩`. Ditto in the next proof.

2021-06-11 01:24 UTC, conal commented on Primitive/Homomorphism.agda
> +      Fₘ-f∘ε≈β∘f : (f : ⊤ ⇨ Bool) {f′ : ⊤ ↠ Bool} →  ⦃ Fₘ f ≡ f′ ⦄ → Fₘ f ∘ ε ≈ β ∘ f′
I'm intrigued with this signature! What motivates you to introduce both `f` and `f′` instead of just one or the other?

2021-06-11 01:24 UTC, conal commented on Primitive/Homomorphism.agda
> +        ≈˘⟨ assoc ⟩
I think you can eliminate this `assoc` step if you start with `∘≈ʳ identityˡ`. Likewise in the `F-cond` proof above.

2021-06-11 01:24 UTC, conal commented on Primitive/Homomorphism.agda
> +        ≡⟨ _≡_.refl ⟩
I like that you start with `ε`, `μ`, and `β`, and then exploit them being equal to `id`.

2021-06-11 01:31 UTC, sseefried commented on Primitive/Homomorphism.agda
> +      Fₘ-f∘ε≈β∘f : (f : ⊤ ⇨ Bool) {f′ : ⊤ ↠ Bool} →  ⦃ Fₘ f ≡ f′ ⦄ → Fₘ f ∘ ε ≈ β ∘ f′
Originally I wrote this as `Fₘ-f∘ε≈β∘f : (f : ⊤ ⇨ Bool) → Fₘ f ∘ ε ≈ β ∘ Fₘ` f but I didn't like this because I felt it didn't "look like" the proof I was trying to do.

e.g. `Fₘ false ∘ ε ≈ β ∘ Fₘ false` does not look the same as `Fₘ false ∘ ε ≈ β ∘ false` which is what I was trying to prove.

Now, I know they are equivalent but I wasn't happy with the way the signature looked. It didn't tell me enough.

2021-06-11 20:00 UTC, conal commented on Primitive/Homomorphism.agda
> +        ≈˘⟨ assoc ⟩
@sseefried Would you like to try this proof-shortening idea before I merge? If not, I'll probably do it myself after merging.

2021-06-11 21:13 UTC, sseefried commented
I'll have a go first

-------- Original Message --------
On 12 Jun 2021, 06:00, Conal Elliott wrote:

> @conal commented on this pull request.
>
> ---------------------------------------------------------------
>
> In [Primitive/Homomorphism.agda](https://github.com/conal/agda-hardware/pull/12#discussion_r650234658):
>
>> +          f′ ∘ ε
> +        ≈⟨ identityʳ ⟩
> +          f′
> +        ≈˘⟨ identityˡ ⟩
> +          id ∘ f′
> +        ≡⟨⟩
> +          β ∘ f′
> +        ∎
> +      Fₘ-f∘μ∘β⊗β≈β∘f : (f : Bool × Bool ⇨ Bool) {f′ : Bool × Bool ↠ Bool} → ⦃ Fₘ f ≡ f′ ⦄
> +                     → Fₘ f ∘ μ {a = Bool} {b = Bool} ∘ (β ⊗ β) ≈ β ∘ f′
> +      Fₘ-f∘μ∘β⊗β≈β∘f f {f′} ⦃ _≡_.refl ⦄ =
> +        begin
> +          Fₘ f ∘ μ {a = Bool} {b = Bool} ∘ (β ⊗ β)
> +        ≡⟨ _≡_.refl ⟩
> +          f′ ∘ id ∘ (id ⊗ id)
> +        ≈˘⟨ assoc ⟩
>
> ***@***.***(https://github.com/sseefried) Would you like to try this proof-shortening idea before I merge? If not, I'll probably do it myself after merging.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, [view it on GitHub](https://github.com/conal/agda-hardware/pull/12#discussion_r650234658), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AAA5TLQOW52SVHSW7GPGGPLTSJTOZANCNFSM46PVJ4WQ).

2021-06-11 23:26 UTC, merged

2021-06-11 23:26 UTC, conal commented
Terrific! Thanks, @sseefried .

2021-06-12 20:08 UTC, conal commented
Closes #6.