Function instances and Cartesian laws
conal/agda-hardware pull request #7
Opened 2021-06-07 16:00 UTC by bolt12

This PR attempts to tackle #4 and #5 . I am mostly looking for improvement suggestions on how to go from this first attempt (still a but rusty with Agda).

2021-06-07 19:31 UTC, conal requested changes
Thanks for the PR!

2021-06-07 19:31 UTC, conal commented on Categorical/Laws.agda
> +    elim-exr : ∀ {f : a ⇨ b} {g : a ⇨ c} -> exr ∘ ( f ▵ g ) ≈ g
I'd go for more specific names, e.g., `exl∘▵` and `exr∘▵`.

I'd drop the spaces just inside the parentheses, changing "`( f ▵ g )`" to "`(f ▵ g)`". Agda's lexical flexibility  requires spaces in many places, but not immediately after "`(`" and before "`)`".

Otherwise, looks fine.

2021-06-07 19:31 UTC, conal commented on Functions/Laws.agda
> +      }
I like the visual style of aligning the opening brace, the semicolons, and the closing brace. The instance definitions in `Functions.Raw` provide examples.

2021-06-07 19:31 UTC, conal commented on Functions/Laws.agda
> +      }
I’d drop the unused explicit implicit parameters here and rename the explicit parameters more informatively, e.g.,

``` agda
∘≈ = λ {k = k} h≈k f≈g → trans h≈k (cong k f≈g)
```

Naming `k` here allows omitting the previous implicits. Sometimes Agda is unhappy with this kind of recipe, and I haven’t tried it in this case.

Since `trans` is a form of sequential composition and often gets chained, I tend to like the `_•_` form defined in `Equivalent`, so

``` agda
∘≈ = λ {k = k} h≈k f≈g → cong k f≈g • h≈k 
```

Even prettier might be to really formulate equivalence relations as a `Category` instance, and use `_∘_` instead of `_•_`. On the other hand, my first attempt at doing so broke instance inference pretty badly.

2021-06-07 19:31 UTC, conal commented on Functions/Laws.agda
> +      }
As above with alignment, `trans`, implicits, and equivalence-valued variable names.

2021-06-07 19:31 UTC, conal commented on Functions/Laws.agda
> +      }
I'd use `h a ,_` and `_, g a`.

2021-06-07 19:49 UTC, conal commented on Categorical/Laws.agda
> +    elim-exr : ∀ {f : a ⇨ b} {g : a ⇨ c} -> exr ∘ ( f ▵ g ) ≈ g
One more: I prefer "`→`" over "`->`".

2021-06-08 08:56 UTC, bolt12 commented on Categorical/Laws.agda
> +    elim-exr : ∀ {f : a ⇨ b} {g : a ⇨ c} -> exr ∘ ( f ▵ g ) ≈ g
Great naming 😄  I will change to that!

2021-06-08 09:27 UTC, bolt12 commented on Functions/Laws.agda
> +      }
Ah nice!! But, hmm it seems `_•_` does not type check correctly so I can not use it. It expects `f g h` to be of the same type, it seems feasible, I am just not sure what can I do to make the compiler happy

2021-06-08 09:27 UTC, bolt12 commented on Functions/Laws.agda
> +      }
Got it!

2021-06-08 09:38 UTC, bolt12 commented on Categorical/Laws.agda
> +    elim-exr : ∀ {f : a ⇨ b} {g : a ⇨ c} -> exr ∘ ( f ▵ g ) ≈ g
Thanks! Keep bugging me with these spacing and unicode issues 😄

2021-06-08 14:34 UTC, conal commented on Functions/Laws.agda
> +                                                        (cong≡ (_, g a) h≈k)
Try `cong₂` from `Relation.Binary.PropositionalEquality.Core` (re-exported from `Relation.Binary.PropositionalEquality`).

I’d drop the local `▵≈-aux` and put the definition directly into the `record` expression: “▵≈ = λ h≈k f≈g → cong₂ …\`”.

Ditto for `∘≈`.

2021-06-08 14:34 UTC, conal commented on Functions/Laws.agda
> +      }
Oh, yes. I think the `trans` you're using here is on `_≡_`, not on morphisms.

2021-06-08 15:45 UTC, bolt12 commented on Functions/Laws.agda
> +                                                        (cong≡ (_, g a) h≈k)
`cong₂` is very nice, thanks!

> Although I’m inclined to make definitions terse in this way to reduce visual noise, I guess doing so makes it a little less clear what exactly is going on.

I can get rid of the visual noise if you prefer!

2021-06-08 19:50 UTC, conal commented on Functions/Laws.agda
> +                                                        (cong≡ (_, g a) h≈k)
> I can get rid of the visual noise if you prefer!

Yes, please, and then I'll merge.

2021-06-08 19:57 UTC, bolt12 commented on Functions/Laws.agda
> +                                                        (cong≡ (_, g a) h≈k)
Done! 😄

2021-06-08 21:06 UTC, merged

2021-06-08 21:21 UTC, conal commented
Thanks for the contribution, @bolt12 !

I did [a little tidying](https://github.com/conal/agda-hardware/commit/1d279eb758bc595818363391bd2b865c2c9706c5).

2021-06-08 21:23 UTC, conal commented
One thing puzzles me. In https://github.com/conal/agda-hardware/blob/1d279eb758bc595818363391bd2b865c2c9706c5/Functions/Laws.agda#L23 I tried removing the outer, pattern-lambda braces, but Agda didn't interpret the `{k = k}` parameter as I expected:

    /Users/conal/Agda/Hardware/Functions/Laws.agda:23,59-60
    Set !=< (_A_14 → _B_16)
    when checking that the expression k has type _A_14 → _B_16

I'm guessing there's a subtlety about regular lambda vs pattern lambda that I've not understood.